name: Deploy to Deno

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install deployctl
        run: npm install -g deployctl

      - name: Deploy to Deno
        run: |
          deployctl deploy \
            --project=rap-poster-bot \
            --token=${{ secrets.DENO_DEPLOY_TOKEN }} \
            --env TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            --env HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }} \
            --env UNSPLASH_ACCESS_KEY=${{ secrets.UNSPLASH_ACCESS_KEY }} \
            --env CHANNEL_ID=${{ secrets.CHANNEL_ID }} \
            bot.js