name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Установка Deno
        run: |
          curl -fsSL https://deno.land/install.sh  | sh

      - name: Добавление Deno в PATH
        run: echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Установка deployctl
        run: |
          deno install -gArf jsr:@deno/deployctl

      - name: Деплой на Deno Deploy
        run: |
          deployctl deploy \
            --project=rap-poster-bot \
            --token=${{ secrets.DENO_DEPLOY_TOKEN }} \
            --env TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            --env HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }} \
            --env UNSPLASH_ACCESS_KEY=${{ secrets.UNSPLASH_ACCESS_KEY }} \
            --env CHANNEL_ID=${{ secrets.CHANNEL_ID }} \
            --env MODEL_NAME=${{ secrets.MODEL_NAME }} \
            bot.js